remote_theme: mmistakes/minimal-mistakes@4.28.1
minimal_mistakes_skin: default
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-sitemap
title: Benjamin's Portfolio
name: Benjamin

author:
  name: "Benjamin"
  avatar: "/assets/images/avatar.jpg"
  bio: "CS graduate focused on cybersecurity and IT."
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/benjamin-lord-0495962b2/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/benjamin6700"
